from .allocation import Ecospold1AllocationTestCase
from .biosphere import BiosphereNormalizationTestCase
from .simapro_name_splitting import NameSplittingTestCase
from .simapro_normalization import SPNormalizationTestCase
